name: AAR Publish

on:
  workflow_dispatch:
    inputs:
      libraryVersion:
        description: 'Library Version'
        required: true
        default: ''
      packageVersion:
        description: 'Package Version'
        required: true
        default: ''

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Assemble Resources
      run: |
            chmod +x pre-build.sh
            ./pre-build.sh
      env:
        VERSION: "${{github.event.inputs.libraryVersion}}"
         
    - name: Set up JDK 8
      uses: actions/setup-java@v2
      with:
        java-version: '8'
        distribution: 'adopt'
        
    - name: Gradle Wrapper
      run: gradle wrapper
    
    - name: Build with Gradle
      run: gradle build -PlexVersion=${{github.event.inputs.packageVersion}}

    - name: Release Package
      uses: "marvinpinto/action-automatic-releases@latest"
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        automatic_release_tag: "${{ github.events.inputs.packageVersion }}"
        prerelease: false
        files: lexactivator/build/outputs/aar/lexactivator-release.aar      
      
# 
#    - name: Set up JDK 8
#      uses: actions/setup-java@v2
#      with:
#        java-version: '8'
#        distribution: 'adopt'
#        server-id: ossrh
#        server-username: OSSRH_USERNAME
#        server-password: OSSRH_PASSWORD
#        gpg-private-key: ${{ secrets.GPG_PRIVATE_KEY }}
#        gpg-passphrase: GPG_PASSPHRASE
                 
#    - name: Publish with Gradle
#      env:
#        GPG_PASSPHARSE: ${{ secrets.GPG_PASSPHARSE }}
#        GPG_PUBLIC_KEY: ${{ secrets.GPG_PUBLIC_KEY }}
#        OSSRH_USERNAME: ${{ secrets.OSSRH_USERNAME }}
#        OSSRH_PASSWORD: ${{ secrets.OSSRH_PASSWORD }}
#        SIGNING_FILE: ${{ secrets.GPG_PRIVATE_KEY }}
#      run: gradle publish -PlexVersion=${{github.event.inputs.Version}}          
