name: Test Publish

on:
    pull_request:
        branches:
            - main
            - develop

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Assemble Resources
      run: ./download-libs.sh
      
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '17'
        cache: 'gradle'
        
    - name: Gradle Wrapper
      run: gradle wrapper
                 
    - name: Publish with Gradle
      run: ./gradlew lexactivator:publishTestPublicationToMavenLocal --info --warning-mode all      
